/**
 * This module provides client-side functionality for the Udibo React App framework.
 * It handles hydration of server-rendered content, routing setup, error handling,
 * and development tools like hot reloading.
 *
 * This module is meant for internal use only and is typically only imported by
 * the `_main.tsx` file in the routes directory that is generated by the build script.
 *
 * @module
 */
import { lazy as reactLazy, startTransition, StrictMode } from "react";
import type { ComponentType, LazyExoticComponent } from "react";
import * as reactHelmetAsync from "react-helmet-async";
const reactHelmetAsyncFixed = reactHelmetAsync;
const { HelmetProvider } = reactHelmetAsyncFixed.default ??
  reactHelmetAsync;
import { hydrateRoot } from "react-dom/client";
import { createBrowserRouter, RouterProvider } from "react-router";
import type { RouteObject } from "react-router";

import { type AppWindow, isDevelopment } from "./env.ts";
import { ErrorContext, InitialStateContext } from "./context.ts";
import { HttpError, withErrorBoundary } from "./error.tsx";
import type { ErrorBoundaryProps, FallbackProps } from "./error.tsx";
import { getLogger } from "./log.ts";

/**
 * Configuration options for hydrating the application in the browser.
 */
export interface HydrateOptions {
  /**
   * The React Router route configuration for the application.
   * This is automatically generated by the build script from your application's routes
   * and exported as the default export from `_main.tsx` in the routes directory.
   */
  route: RouteObject;
}
type AppOptions = HydrateOptions;

/**
 * A React component that serves as the root of the application.
 * It sets up the necessary providers for routing, error handling, and state management.
 * In development mode, it also configures live reload functionality.
 *
 * @param options - Configuration options for the application.
 */
function App<
  SharedState extends Record<string | number, unknown> = Record<
    string | number,
    unknown
  >,
>(options: AppOptions) {
  const log = getLogger();
  const { route } = options;
  const router = createBrowserRouter([route]);
  const rawError = (window as AppWindow).app?.error;
  const { stack, ...errorOptions } = rawError ?? {};
  const error = rawError && new HttpError(errorOptions);
  if (error) {
    if (typeof stack === "string") {
      error.stack = stack;
    }
    log.error("Server error", error);
  }

  if (isDevelopment()) {
    const devPort = (window as AppWindow).app?.devPort ?? 9001;
    const source = new EventSource(`http://localhost:${devPort}/live-reload`);
    source.addEventListener("open", () => {
      log.info("Live reload: Waiting for change");
    });
    source.addEventListener("close", () => {
      log.info("Live reload: Stopped");
    });
    source.addEventListener("error", (event) => {
      log.error("Live reload: Error", event);
    });
    source.addEventListener("reload", () => {
      log.info("Live reload: Reloading");
      location.reload();
    });

    globalThis.addEventListener("beforeunload", () => source.close());
  }

  const initialState = (window as AppWindow<SharedState>).app?.initialState ??
    {} as SharedState;
  const appErrorContext = { error };
  return (
    <StrictMode>
      <HelmetProvider>
        <ErrorContext.Provider value={appErrorContext}>
          <InitialStateContext.Provider value={initialState}>
            <RouterProvider router={router} />
          </InitialStateContext.Provider>
        </ErrorContext.Provider>
      </HelmetProvider>
    </StrictMode>
  );
}

/**
 * Hydrates the application in the browser, turning the server-rendered HTML
 * into an interactive single-page application (SPA).
 *
 * The hydration process is deferred using requestIdleCallback (or setTimeout as a fallback)
 * to avoid blocking the main thread during initial page load.
 *
 * Example usage:
 * ```tsx
 * import { hydrate } from "@udibo/react-app/client";
 * import route from "./routes/_main.tsx";
 *
 * hydrate({ route });
 * ```
 *
 * @param options - Configuration options for hydration.
 */
export function hydrate<
  SharedState extends Record<string | number, unknown> = Record<
    string | number,
    unknown
  >,
>(options: HydrateOptions): void {
  const { route } = options;
  const hydrate = () =>
    startTransition(() => {
      hydrateRoot(
        document.getElementById("root"),
        <App<SharedState> route={route} />,
      );
    });

  if (typeof requestIdleCallback !== "undefined") {
    requestIdleCallback(hydrate);
  } else {
    // Safari doesn't support requestIdleCallback
    // https://caniuse.com/requestidlecallback
    setTimeout(hydrate, 1);
  }
}

/**
 * Represents a route file that exports a React component and optional error handling configuration.
 */
export type RouteFile = {
  /** The main React component for the route. */
  default: ComponentType;
  /**
   * An optional error fallback component that will be rendered by the ErrorBoundary
   * when an error occurs within this route's component tree.
   */
  ErrorFallback?: ComponentType<FallbackProps>;
  /**
   * An optional boundary identifier for the ErrorBoundary.
   * If provided along with ErrorFallback, this will override the default boundary.
   * This is useful for associating server-side errors with the correct ErrorBoundary.
   */
  boundary?: string;
};

/**
 * Creates a lazily-loaded component with automatic error boundary configuration.
 * This is used internally by the build process to set up route components with proper error handling.
 *
 * The function can be called in two ways:
 * 1. With just a factory function that returns the route module
 * 2. With a boundary string and a factory function
 *
 * When the component is loaded, it will automatically be wrapped in an ErrorBoundary
 * if the route module exports an ErrorFallback component or boundary string.
 *
 * @param boundary - A boundary string to use for the ErrorBoundary.
 * @param factory - A factory function that returns the route module.
 * @returns A lazily-loaded React component with error handling configured.
 */
export function lazy<
  T extends RouteFile,
>(factory: () => Promise<T>): LazyExoticComponent<ComponentType>;
export function lazy<
  T extends RouteFile,
>(
  boundary: string,
  factory: () => Promise<T>,
): LazyExoticComponent<ComponentType>;
export function lazy<
  T extends RouteFile,
>(
  boundaryOrFactory?: string | (() => Promise<T>),
  factory?: () => Promise<T>,
): LazyExoticComponent<ComponentType> {
  let boundary = typeof boundaryOrFactory === "string"
    ? boundaryOrFactory
    : undefined;
  if (typeof boundaryOrFactory !== "string") factory = boundaryOrFactory;
  return reactLazy(async () => {
    try {
      const { default: Component, ErrorFallback, boundary: boundaryOverride } =
        await factory!();
      const errorBoundaryProps = {
        FallbackComponent: ErrorFallback,
      } as ErrorBoundaryProps;
      if (boundaryOverride) boundary = boundaryOverride;
      if (boundary) errorBoundaryProps.boundary = boundaryOverride ?? boundary;

      return {
        default: errorBoundaryProps.FallbackComponent
          ? withErrorBoundary(Component, errorBoundaryProps)
          : Component,
      };
    } catch (error) {
      const log = getLogger();
      log.error("Error loading component", error, { boundary });
      (window as AppWindow).location.reload();
      throw error;
    }
  });
}
