FROM postgres:17

# Install build dependencies
RUN apt-get update \
    && apt-get install -y \
        build-essential \
        git \
        postgresql-server-dev-17 \
        pkg-config

# Clone and install pg_uuidv7
RUN git clone https://github.com/fboulnois/pg_uuidv7.git \
    && cd pg_uuidv7 \
    && make \
    && make install

# Cleanup
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /pg_uuidv7
