name: Deploy
on:
  workflow_call:
    inputs:
      app-directory:
        description: The directory containing the application to deploy
        type: string
        default: ''
      entrypoint:
        description: The entrypoint file for running your application
        type: string
        default: 'main.ts'
      project:
        description: The Deno Deploy project to deploy to
        required: true
        type: string
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Build
        run: deno task build-prod
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ inputs.project }}
          entrypoint: '${{ inputs.app-directory }}/${{ inputs.entrypoint }}'
