name: Deploy
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        default: '.'
      app-directory:
        type: string
        default: '.'
      entrypoint:
        type: string
        default: 'main.ts'
      project:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Build
        working-directory: ${{ inputs.working-directory }}
        run: deno task build-prod
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ inputs.project }}
          root: ${{ inputs.working-directory }}
          entrypoint: '${{ inputs.app-directory }}/${{ inputs.entrypoint }}'
