name: CI/CD
on:
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: Repository codecov token
        required: false
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      project: udibo-react-app
      app-directory: example
