name: Release
on:
  workflow_call:
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Release
        if: env.RELEASE_VERSION != ''
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
